#include <stdio.h>
#include <string.h>

/*
-- Desription:
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"

LeetCode: https://leetcode.com/problems/find-the-difference/description/

-- Solution:
You can iterate through both strings s and t and use an array or a hash table to count the frequency of each character in both strings. Then, you can compare the character frequencies to find the character that was added to t.
*/

char findTheDifference(char *s, char *t)
{
    int char_count[26] = {0}; // Assuming lowercase English letters

    // Count characters in string s
    for (int i = 0; i < strlen(s); i++)
    {
        char_count[s[i] - 'a']++;
    }

    // Update character counts for string t
    for (int i = 0; i < strlen(t); i++)
    {
        char_count[t[i] - 'a']--;
    }

    // Find the character with a count of -1 (added to t)
    for (int i = 0; i < 26; i++)
    {
        if (char_count[i] == -1)
        {
            return (char)('a' + i);
        }
    }

    return '\0'; // No added character found
}

int main()
{
    char s1[] = "abcd";
    char t1[] = "abcde";
    printf("%c\n", findTheDifference(s1, t1)); // Output: 'e'

    char s2[] = "";
    char t2[] = "y";
    printf("%c\n", findTheDifference(s2, t2)); // Output: 'y'

    return 0;
}
